# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6d202ab59ed5475f9ce9b86169aea42a3760499b545f4cca331a0250275b4442ae5e21e979975fc63bc2fa1a341a770ffac537918e746f4e4c94b8202b6ac61

test:
  secret_key_base: bfe5949d925dba2685753ee0feb8b7b2d30826ff3d23567874a80bcd3159be10b0f0c5b8f69f3c5d6052d7622a733672b24033a749b3bf8fe45e0f388c6d6e4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
